FROM caddy:{{ caddy_version }}-builder AS builder

ENV GOPROXY=https://goproxy.io,direct
ENV CGO_ENABLED=0

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2@{{ caddy_docker_proxy_version }}

FROM caddy:{{ caddy_version }}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

ENTRYPOINT ["caddy"]
CMD ["docker-proxy"]
